services:
  postgres:
    image: postgres:16-alpine
    container_name: saquero_ordercore_db
    environment:
      POSTGRES_DB: ordercore
      POSTGRES_USER: ordercore_user
      POSTGRES_PASSWORD: ordercore_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ordercore_user -d ordercore"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: saquero_ordercore_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@saquero.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: